### ISSUE TITLE
Waypoint questions should be able to get submitted again

### ISSUE THREAD

**Issue by luwen-huang** [wombats-writing-code/fbw-student-app#11]
right now, I think the scaffolding doesn't show a Waypoint question twice. so:

1) do the full scaffold for one Target, i.e. get all of them wrong
2) try another Target. when you get it wrong, you don't get the Waypoints again.

**Comment by cjshawMIT** [comment]
What is the desired / expected behavior? Scaffolding will not show a waypoint twice, unless it runs out of other questions. I wasn’t clear from the issue description if you expect to see duplicate waypoints and do not, or if you don’t want to ever see duplicate waypoints? Or, do you want it to not try all other questions, first, before turning to duplicates (i.e. always a random sampling, without caring about possible duplicates)?

**Comment by cjshawMIT** [comment]
This is a bug report -- duplicate waypoints aren't showing up at all in the second target, when you get the first target wrong.

**Comment by cjshawMIT** [comment]
Currently this only works when moving backwards ... i.e. starting with T3, if you get that wrong, and then move to T2, you can get the same waypoint again. But if you start at T1, you will not get the same waypoint for T2 or T3 -- no waypoint is generated.

**Comment by cjshawMIT** [comment]
I believe this is working in the latest master. No scaffold back implemented yet.
